# Projeto 3

## Bibliotecas

- `pip install pandas`
- `pip install openpyxl`
- `pip install plotly`

### Imports

In [ ]:
from pathlib import Path

import pandas as pd
import plotly.express as px

## Carregando os dados do Excel

In [ ]:
DATA_DIR = Path('data')
NEW_DATA_DIR = Path('new_data')

In [104]:
df = pd.read_excel(DATA_DIR / 'vendas.xlsx')

# Análises exploratórias

Visualizando as primeiras linhas

In [98]:
df

,id_pedido,data,loja,cidade,estado,regiao,tamanho,local_consumo,preco,forma_pagamento,ano_mes
0,PED1994,2020-01-01,Loja 4,Santos,São Paulo,Sudeste,300ml,Consumo no local,5,Dinheiro,2020-01
1,PED2246,2020-01-01,Loja 6,Florianópolis,Santa Catarina,Sul,500ml,Consumo no local,11,Débito,2020-01
2,PED3876,2020-01-01,Loja 3,Rio de Janeiro,Rio de Janeiro,Sudeste,300ml,Delivery,7,Crédito,2020-01
3,PED4352,2020-01-01,Loja 1,Fortaleza,Ceará,Nordeste,1000ml,Consumo no local,7,Débito,2020-01
4,PED8633,2020-01-01,Loja 5,São Paulo,São Paulo,Sudeste,200ml,Delivery,9,Crédito,2020-01
...,...,...,...,...,...,...,...,...,...,...,...
69995,PED67084,2022-12-31,Loja 6,Florianópolis,Santa Catarina,Sul,500ml,Consumo no local,11,Crédito,2022-12
69996,PED67857,2022-12-31,Loja 3,Rio de Janeiro,Rio de Janeiro,Sudeste,200ml,Consumo no local,7,Pix,2022-12
69997,PED69171,2022-12-31,Loja 4,Santos,São Paulo,Sudeste,500ml,Consumo no local,5,Dinheiro,2022-12
69998,PED69229,2022-12-31,Loja 4,Santos,São Paulo,Sudeste,300ml,Consumo no local,9,Pix,2022-12
69999,PED69356,2022-12-31,Loja 1,Fortaleza,Ceará,Nordeste,300ml,Delivery,9,Pix,2022-12

**Variáveis:**
- **Data do Pedido (Ano-Mês-Dia)**: Data em que o pedido foi realizado.
- **ID do Pedido**: Identificador único do pedido.
- **Loja**: Nome ou número da loja onde o pedido foi realizado.
- **Cidade**: Cidade onde a loja está localizada.
- **Estado**: Estado onde a cidade está localizada.
- **Região**: Região do Brasil onde o estado está localizado.
- **Tamanho do Produto**: Tamanho do produto vendido (ex.: 300ml, 500ml, etc.).
- **Tipo de Consumo**: Se o consumo foi no local ou delivery.
- **Quantidade**: Quantidade de produtos no pedido.
- **Forma de Pagamento**: Método de pagamento utilizado.
- **Data (Ano-Mês)**: Mês e ano do pedido (agregado).

Formato do conjunto de dados

In [ ]:
df.shape

Visualizando informações das colunas

In [ ]:
df.info()

Selecionando colunas

In [ ]:
df[["cidade", "estado"]]

## Estatísticas descritivas

In [102]:
df.describe()

                                data         preco
count                          70000  70000.000000
mean   2021-10-01 20:36:10.697142784      8.355200
min              2020-01-01 00:00:00      5.000000
25%              2021-01-01 00:00:00      7.000000
50%              2022-01-02 00:00:00      7.000000
75%              2022-07-02 00:00:00     11.000000
max              2022-12-31 00:00:00     13.000000
std                              NaN      2.653061

Gerando estatísticas descritivas para todas as colunas

In [103]:
df.describe(include='all')

,id_pedido,data,loja,cidade,estado,regiao,tamanho,local_consumo,preco,forma_pagamento,ano_mes
count,70000,70000,70000,70000,70000,70000,70000,70000,70000.000000,70000,70000
unique,70000,NaN,6,6,4,3,5,2,NaN,4,36
top,PED1994,NaN,Loja 4,Santos,São Paulo,Sudeste,300ml,Consumo no local,NaN,Crédito,2022-03
freq,1,NaN,13483,13483,25660,44581,20475,35099,NaN,26063,3108
mean,NaN,2021-10-01 20:36:10.697142784,NaN,NaN,NaN,NaN,NaN,NaN,8.355200,NaN,NaN
min,NaN,2020-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN
25%,NaN,2021-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,NaN,NaN
50%,NaN,2022-01-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,NaN,NaN
75%,NaN,2022-07-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,11.000000,NaN,NaN
max,NaN,2022-12-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.653061,NaN,NaN

## Análises

Contagem de vendas por lojas

In [ ]:
df["loja"].value_counts()

In [ ]:
df["cidade"].value_counts()

In [ ]:
df["forma_pagamento"].value_counts()

### Agrupando dados

Faturamento por loja

In [ ]:
df.groupby("loja")["preco"].sum()

Faturamento por forma de pagamento

In [ ]:
df.groupby("forma_pagamento")["preco"].sum()

Faturamento

In [ ]:
grouped = df.groupby(["estado", "cidade", "loja", "forma_pagamento"])["preco"].sum()
grouped.to_excel(DATA_DIR / "faturamento.xlsx")

# Visualização de dados

In [ ]:
def plot_histogram(column: str, df: pd.DataFrame) -> None:
    plot = px.histogram(
        df,
        x=column,
        y="preco",
        text_auto=True,
        title=f"Faturamento por {column}",
        color="forma_pagamento"
    )
    plot.update_layout(
        xaxis_title=column.title(),
        yaxis_title="Total de vendas",
        title={
            'text': f"Faturamento por {column}",
            'y': 0.9,
            'x': 0.5,
            'xanchor': 'center',
            'yanchor': 'top'
        }
    )
    plot.show()
    plot.write_html(DATA_DIR / f"faturamento-por-{column}.html")

In [ ]:
columns = ["loja", "cidade", "estado", "tamanho", "local_consumo"]

for column in columns:
    plot_histogram(column, df)

**Gráfico de Barras por Tipo de Consumo e Tamanho do Produto**

Comparar a quantidade de pedidos por diferentes tamanhos de produto e tipo de consumo (no local vs delivery).

In [101]:
df_grouped = df.groupby(["tamanho", "local_consumo"]).size().reset_index(name="count")

fig = px.bar(
    df_grouped,
    x="tamanho",
    y="count",
    color="local_consumo",
    title="Local de Consumo x Tamanho do Copo",
)
fig.update_layout(
    xaxis_title="Tamanho do copo",
    yaxis_title="Quantidade de pedidos",
    title={
        'text': "Local de Consumo x Tamanho do Copo",
        'y': 0.9,
        'x': 0.5,
        'xanchor': 'center',
        'yanchor': 'top'
    }
)

fig.show()

A quantidade entre o local de consumo com os tamanhos dos copos está equilibrada.

Porém, é possível notar que, existe uma diferença considerável referente ao tamanho do copo com a quantidade que ele é pedido.

Vale a pena uma análise mais detalhada referente as regiões (loja, cidade, estado) em que cada copo é mais pedido.

# Eu quero ser Expert em Python